using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NOW.FeatureFlagExtensions.FeatureManagement.FeatureFlagGenerator.Tests.TestConfigurations.AppSettings
{
    public static class Expected
    {
        public const string GeneratedCode = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: RuntimeVersionKey
//     Generator Version: GeneratorVersionKey
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TestFeatures
{
    /// <summary>
    /// Available feature flags/toggles, https://www.martinfowler.com/articles/feature-toggles.html
    /// </summary>
    public static class FeatureFlagsGenerated
    {
        /// <summary>
        /// Experiment Toggles are used to perform multivariate or A/B testing.
        /// </summary>
        public static class ExperimentFlags
        {
/*__ExperimentFlags__*/
        }

        /// <summary>
        /// Ops Toggles are used to control operational aspects of our system's behavior.
        /// </summary>
        public static class OpsFlags
        {
/*__OpsFlags__*/
        }

        /// <summary>
        /// Permission Toggles are used to change the features or product experience that
        /// certain users receive.
        /// </summary>
        public static class PermissionFlags
        {
/*__PermissionFlags__*/
        }

        /// <summary>
        /// Release Toggles allow incomplete and untested code-paths to be shipped to production,
        /// as latent code which may never be turned on.
        /// </summary>
        public static class ReleaseFlags
        {
            public const string TestFeatureOne = nameof(TestFeatureOne);
            public const string TestFeatureTwo = nameof(TestFeatureTwo);
            public const string TestFeatureThree = nameof(TestFeatureThree);

        }
    }
}
";
    }
}
