namespace NOW.FeatureFlagExtensions.FeatureManagement.FeatureFlagGenerator
{
    public static class Constants
    {
        public const string RuntimeVersionKey = nameof(RuntimeVersionKey);
        public const string GeneratorVersionKey = nameof(GeneratorVersionKey);

        public const string FeatureFlagFormat = "            public const string {0} = nameof({0});";
        public const string ExperimentFlagsKey = "/*__ExperimentFlags__*/";
        public const string OpsFlagsKey = "/*__OpsFlags__*/";
        public const string PermissionFlagsKey = "/*__PermissionFlags__*/";
        public const string ReleaseFlagsKey = "/*__ReleaseFlags__*/";

        public const string ClassContent = $@"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: {RuntimeVersionKey}
//     Generator Version: {GeneratorVersionKey}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TestFeatures
{{
    /// <summary>
    /// Available feature flags/toggles, https://www.martinfowler.com/articles/feature-toggles.html
    /// </summary>
    public static class FeatureFlagsGenerated
    {{
        /// <summary>
        /// Experiment Toggles are used to perform multivariate or A/B testing.
        /// </summary>
        public static class ExperimentFlags
        {{
{ExperimentFlagsKey}
        }}

        /// <summary>
        /// Ops Toggles are used to control operational aspects of our system's behavior.
        /// </summary>
        public static class OpsFlags
        {{
{OpsFlagsKey}
        }}

        /// <summary>
        /// Permission Toggles are used to change the features or product experience that
        /// certain users receive.
        /// </summary>
        public static class PermissionFlags
        {{
{PermissionFlagsKey}
        }}

        /// <summary>
        /// Release Toggles allow incomplete and untested code-paths to be shipped to production,
        /// as latent code which may never be turned on.
        /// </summary>
        public static class ReleaseFlags
        {{
{ReleaseFlagsKey}
        }}
    }}
}}
";
    }
}